import { writeFileSync } from 'fs';
import { Report, Finding, ReportSummary } from './types.js';

export function buildSummary(findings: Finding[], filesAnalyzed: number, linesOfCode: number): ReportSummary {
  return {
    totalFindings: findings.length,
    critical: findings.filter(f => f.severity === 'critical').length,
    high: findings.filter(f => f.severity === 'high').length,
    medium: findings.filter(f => f.severity === 'medium').length,
    low: findings.filter(f => f.severity === 'low').length,
    info: findings.filter(f => f.severity === 'info').length,
    filesAnalyzed,
    linesOfCode,
  };
}

export function generateJsonReport(report: Report, outputPath: string): void {
  writeFileSync(outputPath, JSON.stringify(report, null, 2));
}

export function generateMarkdownReport(report: Report): string {
  const lines: string[] = [];

  lines.push(`# Krait Security Audit Report`);
  lines.push('');
  lines.push(`**Project**: ${report.projectName}`);
  lines.push(`**Path**: ${report.projectPath}`);
  lines.push(`**Date**: ${report.timestamp}`);
  lines.push(`**Duration**: ${(report.duration / 1000).toFixed(1)}s`);
  lines.push(`**Model**: ${report.model}`);
  lines.push(`**Patterns loaded**: ${report.patternsUsed}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${report.summary.critical} |`);
  lines.push(`| High | ${report.summary.high} |`);
  lines.push(`| Medium | ${report.summary.medium} |`);
  lines.push(`| Low | ${report.summary.low} |`);
  lines.push(`| Info | ${report.summary.info} |`);
  lines.push(`| **Total** | **${report.summary.totalFindings}** |`);
  lines.push('');
  lines.push(`Files analyzed: ${report.summary.filesAnalyzed}`);
  lines.push(`Lines of code: ${report.summary.linesOfCode}`);
  lines.push('');

  if (report.findings.length === 0) {
    lines.push('## Findings');
    lines.push('');
    lines.push('No vulnerabilities found.');
    return lines.join('\n');
  }

  // Findings grouped by severity
  const severityOrder = ['critical', 'high', 'medium', 'low', 'info'] as const;

  for (const severity of severityOrder) {
    const sevFindings = report.findings.filter(f => f.severity === severity);
    if (sevFindings.length === 0) continue;

    lines.push(`## ${severity.charAt(0).toUpperCase() + severity.slice(1)} Findings`);
    lines.push('');

    for (const finding of sevFindings) {
      lines.push(`### ${finding.id}: ${finding.title}`);
      lines.push('');
      lines.push(`**File**: \`${finding.file}:${finding.line}\``);
      lines.push(`**Confidence**: ${finding.confidence}`);
      lines.push(`**Category**: ${finding.category}`);
      if (finding.patternId) {
        lines.push(`**Pattern**: ${finding.patternId}`);
      }
      lines.push('');
      lines.push(`**Description**: ${finding.description}`);
      lines.push('');
      lines.push(`**Impact**: ${finding.impact}`);
      lines.push('');
      lines.push(`**Remediation**: ${finding.remediation}`);
      if (finding.codeSnippet) {
        lines.push('');
        lines.push('**Code**:');
        lines.push('```');
        lines.push(finding.codeSnippet);
        lines.push('```');
      }
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  lines.push('');
  lines.push('*Generated by [Krait](https://github.com/ZealynxSecurity/krait) — AI Security Auditor by Zealynx Security*');

  return lines.join('\n');
}

export function writeMarkdownReport(report: Report, outputPath: string): void {
  const md = generateMarkdownReport(report);
  writeFileSync(outputPath, md);
}
